### ISSUE TITLE
Support for Kailh Choc V2 Switches

### ISSUE THREAD

**Issue by connorbowden** [foostan/crkbd#49] opened 2020-06-01 17:44 UTC
Kailh has released a second version of low profile switches, called Choc V2’s. From what I’ve read, the pin layout is different from both the other version of choc low profile switches and cherry’s low profile switch, which would require a new PCB layout. Will there be an update for Corne’s PCB to support these switches?

Edit: link to the switches  https://www.kailhswitch.com/news/kailh-choc-v-32057417.html

**Comment by filoxo** [comment] 2020-06-11 21:56
Duplicate of #41

**Comment by connorbowden** [comment] 2020-06-12 14:54
@filoxo Link to the first version release of Kailh's low profile switches: https://www.kailhswitch.com/mechanical-keyboard-switches/low-profile-key-switches/dark-yellow-switch.html

Link to the 2nd version of Kailh's low profile switches (the ones I referenced) : https://www.kailhswitch.com/news/kailh-choc-v-32057417.html

**Comment by foostan** [comment] 2020-07-29 02:15
I'm try prototyping for Choc V2. 
![image](https://user-images.githubusercontent.com/736191/88748765-d0fba200-d18c-11ea-883e-b3393171e730.png)

**Comment by MarkCampbell1970** [comment] 2020-10-29 14:25
Hello, Did you have any luck with prototyping PCB. I actually bought some of the choc v2 switches thinking that they would fit on the regular Kailh PCB for low profile switches and obviously that didn't work out. I am not able to find any other board that supports it. I was just wondering if you still planning to making a prototype and if you plan to make it public.
Thank you!

**Comment by CMorooney** [comment] 2021-04-28 14:52
> Hello, Did you have any luck with prototyping PCB. I actually bought some of the choc v2 switches thinking that they would fit on the regular Kailh PCB for low profile switches and obviously that didn't work out. I am not able to find any other board that supports it. I was just wondering if you still planning to making a prototype and if you plan to make it public.
> Thank you!

Same here -- crkbd is my favorite layout/board and I am really looking forward to putting these switches on one! Any news on official compatibility?

**Comment by keyboard-magpie** [comment] 2021-04-28 14:54
Corne light in the main repository has support for choc v2 now @CMorooney https://github.com/foostan/crkbd/tree/master/corne-light

**Comment by CMorooney** [comment] 2021-04-28 14:56
ah, great, thanks @keyboard-magpie ! Perhaps this issue should be closed?

**Comment by markstos** [comment] 2021-04-28 18:42
I'm building a Corne Light with Choc v2 switches now. It's currently with a builder who is debugging some issue. I got my PCB from a Redditor who had several of the prototypes printed for himself and sold one to me. I don't think he has more. (And was located in Sweden, so the shipping cost to the US was about the cost of the PCB).

**Closed** 2021-10-30 07:16 UTC
